context:
  version: "1.11.3"

package:
  name: mkdocs-drawio
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/mkdocs-drawio/mkdocs_drawio-${{ version }}.tar.gz
    sha256: 12d061b03c8449755a693aa2d1a1a351d9d8dc1a3b6a0500b8509bf1c76c6ac4

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - jinja2 >=3.0
    - beautifulsoup4 >=4.0
    - lxml >=4.0
    - mkdocs >=1.4
    - requests >=2.0

tests:
  - python:
      imports:
        - mkdocs_drawio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/tuunit/mkdocs-drawio
  summary: MkDocs plugin for embedding Drawio files
  description: |
    This plugin enables you to embed interactive drawio diagrams in your documentation. Simply add your diagrams like you would any other image.
    Additionally this plugin supports multi page diagrams by using either the page or alt property. To use the page property, you need to use the markdown extension attr_list.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - claudiushaag
